### ISSUE TITLE
Tomahawk loses network connectivitiy

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk#493]
After switching interfaces (wifi->ethernet->different wifi->etc)
Tomahawk loses connectivity, all native http request fail with qt error "Network access is disabled."
Though resolvers doing http queries via webkit still get responses

**Comment by theli-ua** [comment]
This is on OSX, Master, Qt 5.6.0

**Comment by theli-ua** [comment]
Ok, So I was NOT using 5.6.0

Seems like its working just fine with 5.6.0

Not sure what should we do with this issue.
I can keep it open for some days to see if the issue is indeed fixed with 5.6.0

**Comment by dschmidt** [comment]
Yes, please. Otherwise do you notice any differences with qt 5.6? I can update it on the build machine so nightlies are fixed too

**Comment by theli-ua** [comment]
I don't think I noticed any issues with 5.6.0

**Comment by muesli** [comment]
Ok, let's close this for now and reopen should you be able to reproduce it with 5.6 still.

**Comment by theli-ua** [comment]
Mon Apr 25 2016 - 11:50:52 [9]: "Network access is disabled."
```
$ otool -L Tomahawk.app/Contents/MacOS/Tomahawk | grep -i network
	/usr/local/opt/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.6.0, current version 5.6.0)

```
still happens with 5.6.0
though it seems like it doesn't happen as often
